

CREATE USER 'core5429_ihram'@'localhost' IDENTIFIED BY  '***';
GRANT ALL PRIVILEGES ON * . * TO  'core5429_ihram'@'localhost' IDENTIFIED BY '***' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON  `core5429_ihram` . * TO  'core5429_ihram'@'localhost';